version: "3"
services:
  rabbitmq:
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
      - "11883:11883"
      - "18883:18883"
    volumes:
      - ./configs/rabbit.def.json:/etc/rabbitmq/definitions.json:ro
      - ./configs/rabbit.config:/etc/rabbitmq/rabbitmq.config:ro

  postgres:
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bamnner-rotator_server:
    ports:
      - "9001:9090"

volumes:
  pgdata: