name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  run_makefile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: lint code
      run: make lint

    - name: test code
      run: make test

    - name: build code
      run: make build